service: emotion-recognition

custom:
  variables:
    AWS_REGION: us-west-1
    BUCKET_NAME: ucb-sis-image-bucket
    TABLE_NAME: emotion_recognition_records

provider:
  name: aws
  stage: dev
  region: ${self:custom.variables.AWS_REGION}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: 
            - "arn:aws:s3:::${self:custom.variables.BUCKET_NAME}/*"
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource:
            - "Fn::GetAtt": [EmotionRecognitionTable, Arn]
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
    apiKeys:
      - emotion-recognition-api-key
  ecr:
    images:
      appimage:
        path: ./

functions:
  uploader:
    runtime: nodejs16.x
    handler: js-handler.imageUploadHandler
    events:
      - http:
          path: /image
          method: post
          private: true
    environment:
      BUCKET: ${self:custom.variables.BUCKET_NAME}
      
  emotion-get:
    runtime: python3.8
    handler: py-handler.get_emotion_handler
    events:
      - http:
          path: /emotion
          method: get
          private: true
    environment:
      TABLE_NAME: ${self:custom.variables.TABLE_NAME}

  emotion-delete:
    runtime: python3.8
    handler: py-handler.delete_emotion_handler
    events:
      - http:
          path: /emotion
          method: delete
          private: true
    environment:
      TABLE_NAME: ${self:custom.variables.TABLE_NAME}

  emotion:
    image:
      name: appimage
      command:
        - app.emotion_recognition_handler
      entryPoint:
        - "/lambda-entrypoint.sh"
    timeout: 30
    memorySize: 3008
    events:
      - http:
          path: /emotion
          method: post
          private: true
    environment:
      TABLE_NAME: ${self:custom.variables.TABLE_NAME}

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.variables.BUCKET_NAME}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
    EmotionRecognitionTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:custom.variables.TABLE_NAME}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5     